### ISSUE TITLE
Attacking Rooks - URI

### ISSUE THREAD

**Issue by axellbrendow** [GabrielFrizzo/NeedSomething#1]
Opa, tudo bom parceiro ? Desculpe-me pelo incomodo, meu nome é Axell e sou estudante de Ciência da Computação. Vi que você submeteu uma solução para a questão [Attacking Rooks](https://www.urionlinejudge.com.br/judge/en/problems/view/1490) no mês passado e estou há semanas tentando achar uma solução pra essa questão. Tu consegue me dizer como fez ela ? xD

**Comment by GabrielFrizzo** [comment]
Opa, beleza Axell? Vc já ouviu falar em Emparelhamento de Grafo Bipartido? Têm vários algoritmos que resolvem esse mesmo problema, talvez você já conheça algum. Se não, dá uma olhada em Emparelhamento por Caminhos Aumentantes, Hopcroft Karp, ou mesmo Ford Fulkerson.
Sabendo disso, para modelar o grafo bipartido: Um lado do grafo são os pedaços de linhas "livres", o outro são a mesma coisa, para as colunas. Se ainda tiver dificuldades, fico à disposição

**Comment by axellbrendow** [comment]
Opa, vlw pelas dicas. Vou pesquisar sobre como resolver emparelhamento com Ford Fulkerson.

**Comment by axellbrendow** [comment]
Consegui resolver a questão aqui, outra pessoa me ajudou também. Agradeço novamente!

**Comment by GabrielFrizzo** [comment]
Legal! Fico feliz que tenha conseguido
